# -*- coding: utf-8 -*-
"""Experiment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oqW5ayWrYK_Oxb8QC1FmO1rXAPbVjVL9
"""



a=100
b=200
c=a+b
print(c)

